name: Gitea

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: 1.13.7

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: go-gitea/gitea
          ref: v${{ env.RELEASE_VERSION }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          platforms: linux/arm/v6,linux/arm/v7
          push: true
          tags: stelas/gitea-arm:${{ env.RELEASE_VERSION }},stelas/gitea-arm:latest
